-- Oracle 11g XE 스키마 (§3단계 3-1)
-- 실행: python sql/init_db.py
--
-- Oracle 11g 규약 반영:
--   - IDENTITY 컬럼 없음 → SEQUENCE + BEFORE INSERT TRIGGER 로 PK 자동 채움
--   - BOOLEAN 없음 → NUMBER(1) + CHECK (IN 0,1)
--   - FK 컬럼은 자동 인덱스 생성 안 됨 → 필요 시 명시 인덱스
--
-- 각 문장 종료는 "/" 한 줄. init_db.py 의 split_statements 가 이를 기준으로
-- statement 를 분할한다. PL/SQL 블록의 END; 세미콜론은 그대로 유지.


-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE USERS (
  ID              NUMBER PRIMARY KEY,
  USERNAME        VARCHAR2(50) UNIQUE NOT NULL,
  PASSWORD_HASH   VARCHAR2(255) NOT NULL,
  EMAIL           VARCHAR2(120) UNIQUE,
  FULL_NAME       VARCHAR2(100),
  ROLE            VARCHAR2(20) DEFAULT 'inspector'
                  CHECK (ROLE IN ('inspector','manager','admin')),
  IS_ACTIVE       NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  LAST_LOGIN_AT   TIMESTAMP
)
/

CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE OR REPLACE TRIGGER TRG_USERS_BI
BEFORE INSERT ON USERS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_USERS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/


-- ============================================================
-- INSPECTIONS
-- ============================================================
CREATE TABLE INSPECTIONS (
  ID              NUMBER PRIMARY KEY,
  USER_ID         NUMBER,
  FILE_NAME       VARCHAR2(255),
  IMAGE_PATH      VARCHAR2(512),
  HEATMAP_PATH    VARCHAR2(512),
  ANNOTATED_PATH  VARCHAR2(512),
  SEG_PATH        VARCHAR2(512),
  SOURCE          VARCHAR2(20) CHECK (SOURCE IN ('upload','sample')),
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  A3_RATIO        NUMBER(10,6),
  A3_CELLS        NUMBER(5),
  SEG_CRACK       NUMBER(10,6),
  SEG_DELAM       NUMBER(10,6),
  PINHOLE_COUNT   NUMBER(5),
  MS_A3           NUMBER(10,3),
  MS_YOLO         NUMBER(10,3),
  MS_SEG          NUMBER(10,3),
  MS_TOTAL        NUMBER(10,3),
  IS_COLD_START   NUMBER(1) DEFAULT 0 CHECK (IS_COLD_START IN (0,1)),
  STATUS          VARCHAR2(20) DEFAULT 'normal'
                  CHECK (STATUS IN ('normal','alarm','reviewed')),
  REVIEWED_BY     NUMBER,
  REVIEWED_AT     TIMESTAMP,
  CONSTRAINT FK_INSPECTIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT FK_INSPECTIONS_REVIEWED_BY FOREIGN KEY (REVIEWED_BY) REFERENCES USERS(ID)
)
/

CREATE SEQUENCE SEQ_INSPECTIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE OR REPLACE TRIGGER TRG_INSPECTIONS_BI
BEFORE INSERT ON INSPECTIONS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_INSPECTIONS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/


-- ============================================================
-- DETECTIONS  (YOLO 박스 · 검사당 다수)
-- ============================================================
CREATE TABLE DETECTIONS (
  ID              NUMBER PRIMARY KEY,
  INSPECTION_ID   NUMBER NOT NULL,
  X1              NUMBER(7,2),
  Y1              NUMBER(7,2),
  X2              NUMBER(7,2),
  Y2              NUMBER(7,2),
  CONF            NUMBER(5,4),
  ASPECT          NUMBER(7,3),
  ROUNDNESS       NUMBER(5,4),
  CONSTRAINT FK_DETECTIONS_INSP FOREIGN KEY (INSPECTION_ID)
    REFERENCES INSPECTIONS(ID) ON DELETE CASCADE
)
/

CREATE SEQUENCE SEQ_DETECTIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE OR REPLACE TRIGGER TRG_DETECTIONS_BI
BEFORE INSERT ON DETECTIONS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_DETECTIONS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/


-- ============================================================
-- SPC_POINTS  (관리도 시계열)
-- ============================================================
CREATE TABLE SPC_POINTS (
  ID              NUMBER PRIMARY KEY,
  INSPECTION_ID   NUMBER NOT NULL,
  METRIC          VARCHAR2(20),
  CONSTRAINT CHK_SPC_METRIC CHECK (METRIC IN ('a3','seg_crack','pinhole_count')),
  SEQ_NO          NUMBER(7),
  VALUE           NUMBER(10,6),
  EWMA            NUMBER(10,6),
  CENTER          NUMBER(10,6),
  UCL             NUMBER(10,6),
  IS_ALARM        NUMBER(1) DEFAULT 0 CHECK (IS_ALARM IN (0,1)),
  CONSTRAINT FK_SPC_INSP FOREIGN KEY (INSPECTION_ID)
    REFERENCES INSPECTIONS(ID) ON DELETE CASCADE
)
/

CREATE SEQUENCE SEQ_SPC_POINTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE OR REPLACE TRIGGER TRG_SPC_POINTS_BI
BEFORE INSERT ON SPC_POINTS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_SPC_POINTS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/


-- ============================================================
-- FINDINGS  (Advisor 3층 리포트 · 검사당 다수 행)
-- ============================================================
CREATE TABLE FINDINGS (
  ID              NUMBER PRIMARY KEY,
  INSPECTION_ID   NUMBER NOT NULL,
  LAYER           VARCHAR2(20)
                  CHECK (LAYER IN ('observation','interpretation','reference')),
  CONTENT         VARCHAR2(4000),
  CONFIDENCE      VARCHAR2(10),
  SOURCE          VARCHAR2(100),
  CONSTRAINT FK_FINDINGS_INSP FOREIGN KEY (INSPECTION_ID)
    REFERENCES INSPECTIONS(ID) ON DELETE CASCADE
)
/

CREATE SEQUENCE SEQ_FINDINGS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE OR REPLACE TRIGGER TRG_FINDINGS_BI
BEFORE INSERT ON FINDINGS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_FINDINGS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/


-- ============================================================
-- POSTS  (커뮤니티 게시판)
-- ============================================================
CREATE TABLE POSTS (
  ID              NUMBER PRIMARY KEY,
  USER_ID         NUMBER,
  INSPECTION_ID   NUMBER,
  CATEGORY        VARCHAR2(20) DEFAULT 'free'
                  CHECK (CATEGORY IN ('notice','report','qna','free')),
  TITLE           VARCHAR2(200) NOT NULL,
  CONTENT         VARCHAR2(4000),
  VIEW_COUNT      NUMBER(7) DEFAULT 0,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP,
  CONSTRAINT FK_POSTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT FK_POSTS_INSP FOREIGN KEY (INSPECTION_ID) REFERENCES INSPECTIONS(ID)
)
/

CREATE SEQUENCE SEQ_POSTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE OR REPLACE TRIGGER TRG_POSTS_BI
BEFORE INSERT ON POSTS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_POSTS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/


-- ============================================================
-- COMMENTS
-- ============================================================
CREATE TABLE COMMENTS (
  ID              NUMBER PRIMARY KEY,
  POST_ID         NUMBER NOT NULL,
  USER_ID         NUMBER,
  CONTENT         VARCHAR2(1000),
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_COMMENTS_POST FOREIGN KEY (POST_ID)
    REFERENCES POSTS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_COMMENTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
)
/

CREATE SEQUENCE SEQ_COMMENTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/

CREATE OR REPLACE TRIGGER TRG_COMMENTS_BI
BEFORE INSERT ON COMMENTS FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_COMMENTS.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/


-- ============================================================
-- 인덱스 (FK · 조회 자주 쓰이는 컬럼)
-- ============================================================
CREATE INDEX IDX_INSPECTIONS_USER ON INSPECTIONS(USER_ID)
/

CREATE INDEX IDX_INSPECTIONS_CREATED ON INSPECTIONS(CREATED_AT)
/

CREATE INDEX IDX_SPC_METRIC_SEQ ON SPC_POINTS(METRIC, SEQ_NO)
/

CREATE INDEX IDX_POSTS_CAT_CREATED ON POSTS(CATEGORY, CREATED_AT)
/

CREATE INDEX IDX_COMMENTS_POST ON COMMENTS(POST_ID)
/
